### PR TITLE
chore(deps): update deps, fix nsp

### PR DESCRIPTION
**Pull request by vladikoff**

### CODE REVIEW

**Comment by vladikoff** [comment]
Ref:
```
➜  ip-reputation-js-client git:(master) nsp check package.json
(+) 2 vulnerabilities found
┌───────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│               │ Prototype pollution attack                                                                                             │
├───────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Name          │ hoek                                                                                                                   │
├───────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ CVSS          │ 4 (Medium)                                                                                                             │
├───────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Installed     │ 4.2.0                                                                                                                  │
├───────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Vulnerable    │ <= 4.2.0 || >= 5.0.0 < 5.0.3                                                                                           │
├───────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Patched       │ > 4.2.0 < 5.0.0 || >= 5.0.3                                                                                            │
├───────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Path          │ ip-reputation-js-client@2.1.2 > joi@10.2.1 > hoek@4.2.0                                                                │
├───────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ More Info     │ https://nodesecurity.io/advisories/566                                                                                 │
└───────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│               │ Prototype pollution attack                                                                                             │
├───────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Name          │ hoek                                                                                                                   │
├───────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ CVSS          │ 4 (Medium)                                                                                                             │
├───────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Installed     │ 4.2.0                                                                                                                  │
├───────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Vulnerable    │ <= 4.2.0 || >= 5.0.0 < 5.0.3                                                                                           │
├───────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Patched       │ > 4.2.0 < 5.0.0 || >= 5.0.3                                                                                            │
├───────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Path          │ ip-reputation-js-client@2.1.2 > request@2.83.0 > hawk@6.0.2 > hoek@4.2.0                                               │
├───────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ More Info     │ https://nodesecurity.io/advisories/566                                                                                 │
└───────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘


```

**Comment by vladikoff** [comment]
@g-k could you make sure test are passing for you? I was getting some `ECONNREFUSED`

**Comment by g-k** [comment]
Thanks! the tests run against a running tigerblood instance

**Comment by vladikoff** [comment]
@g-k okay! could you please publish a new version to npm ?

**Comment by vladikoff** [comment]
@g-k Ahhh `package-lock` also needs to be updated

**Comment by g-k** [comment]
Published 2.1.3 https://www.npmjs.com/package/ip-reputation-js-client

**Comment by vladikoff** [comment]
Thank you very much for the quick response!

**Pull request merged**
