### PR TITLE
Fix config

### PR DESCRIPTION
**Pull request by g-k**
should fix: https://github.com/mozilla-services/ip-reputation-js-client/issues/3

ran: npm test against a local tigerblood service

### CODE REVIEW

**Comment by g-k** [comment]
The violation test is failing but I think that's a problem with tigerblood and not this PR.

**Comment by g-k** [comment]
Functional Tests pass running against tigerblood master:

```
~/ip-reputation-js-client - [fix-config] » npm test

> ip-reputation-js-client@1.0.1 test /Users/gguthe/ip-reputation-js-client
> scripts/test-local.sh

Running "eslint:files" (eslint) task

Running "copyright:app" (copyright) task

Running "copyright:tests" (copyright) task

Done.
test/local/reputation_service_client_tests.js ....... 29/29
total ............................................... 29/29

  29 passing (1s)

  ok
-----------|----------|----------|----------|----------|----------------|
File       |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
-----------|----------|----------|----------|----------|----------------|
All files  |      100 |       50 |      100 |      100 |                |
 client.js |      100 |       50 |      100 |      100 |                |
-----------|----------|----------|----------|----------|----------------|

/Users/gguthe/ip-reputation-js-client/node_modules/coveralls/bin/coveralls.js:18
        throw err;
        ^
Bad response: 422 {"message":"Couldn't find a repository matching this job.","error":true}
npm ERR! Test failed.  See above for more details.
~/ip-reputation-js-client - [fix-config] » git log --format=oneline -1
2e143f65bfc5fa93a1a1dfb05f3beb8b5f8f7fcb fix(test): test strictSSL set properly
~/ip-reputation-js-client - [fix-config] » 
```

**Comment by g-k** [comment]
This will require a major version bump since it changes the constructor interface.

**Comment by jrgm** [comment]
LGTM. But you might want to iterate on fxa-customs-server to get it to work with this, and see if feels like a nice fit (for that and any future consumer) before npm publishing. For one thing, tests in that repo depend on having a REPUTATION_SERVICE_PORT in addition to a serviceUrl.

**Comment by g-k** [comment]
Yeah, I did some integration work against this branch linked locally on this branch: https://github.com/mozilla/fxa-customs-server/compare/master...g-k:fix-rep-service-config?expand=1

So hopefully, I won't have to touch this again.

**Pull request merged**
